apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-eebv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-eebv@sha256:cfe54165380e8613f5867f8cf4ab95d6a511609e756a73a842596dda408107e6
        name: my-nodejs
        resources: {}
status: {}
